micronaut:
  application:
    name: robot-impl
  server:
    port: 8083
hystrix.stream.enabled: false

consul:
  client:
    registration:
      enabled: true
      check.enabled: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
candlestickListener:
  possible_gap_in_updates_ms: 60_000
  check_time_period_multiplier: 10
grpc:
  client:
    plaintext: true
    discovery:
      enabled: true
  server:
    port: 50052
    keep-alive-time: 3h
    max-inbound-message-size: 1024

robot:
  usdCoin: USDT
  interval: ONE_MINUTE
  stopLoss: 0.3
  takeProfit: 2
  coinsCount: 1
  initialBalance: 25

subscription:
  quoteFilter: USDT
  baseFilter: [BTC, ETH, BNB, ADA, SOL, XRP, DOT, DOGE, LUNA, SHIB, UNI, AVAX, LINK, WBTC, LTC, BCH, ALGO, MATIC, XLM, VET, ATOM, ICP, AXS, FTT, FTM, FIL, ETC, TRX, THETA, BTCB]
  candlestickIntervals: [DAILY]
  updateIntervalSec: 9999999999
robotState:
  robotName: ath-robot-1
  usdCoin: USDT
  defaultUsdBalance: 50
athDivergenceSignalConfig:
  periodLength: 30
  divergenceForBuy: 0.75
riskProcessor:
  maxNumberOfOpenPositions: 1
  maxNumberOfBuyMore: 0
  buyMorePercentOfOpenPosition: 0.5
  buyMoreThreshold: 0
  stopLoss: 0.7
  takeProfit: 1.1
  firstBuyPercent: 1
endpoints:
  health:
    enabled: true
    sensitive: false