micronaut:
  application:
    name: robot-impl
  server:
    port: 8083
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
hystrix.stream.enabled: false

consul:
  client:
    registration:
      enabled: true
      check.enabled: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
candlestickListener:
  possible_gap_in_updates_ms: 60_000
  check_time_period_multiplier: 10
grpc:
  client:
    plaintext: true
    discovery:
      enabled: true
  server:
    port: 50052
    keep-alive-time: 3h
    max-inbound-message-size: 1024

robot:
  enabled: false
  usdCoin: USDT
  interval: TWELVE_HOURLY
  stopLoss: 0.3
  takeProfit: 2
  coinsCount: 1
  initialBalance: 25

subscription:
  quoteFilter: USDT
  baseFilter: [BTC]
  candlestickIntervals: [DAILY]
  updateIntervalSec: 86000000
robotState:
  robotName: ath-robot-1
  usdCoin: USDT
  defaultUsdBalance: 50
athDivergenceSignalConfig:
  periodLength: 30
  divergenceForBuy: 0.15
riskProcessor:
  maxNumberOfOpenPositions: 1
  maxNumberOfBuyMore: 0
  buyMorePercentOfOpenPosition: 0.5
  buyMoreThreshold: 0.8
  stopLoss: 0.9999
  takeProfit: 1.0001
  firstBuyPercent: 1

endpoints:
  health:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false
