micronaut:
  application:
    name: robotImpl
hystrix.stream.enabled: false

candlestickListener:
  possible_gap_in_updates_ms: 60_000
  check_time_period_multiplier: 10
grpc:
  client:
    plaintext: true

robot:
  usdCoin: USDT
  interval: TWELVE_HOURLY
  stopLoss: 0.3
  takeProfit: 1.2
  coinsCount: 1