apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-impl-config
data:
  application.yml: |
    micronaut:
      application:
        name: robot-impl
      server:
        port: 8083
    hystrix.stream.enabled: false

    consul:
      client:
        registration:
          enabled: true
          check.enabled: false
          prefer-ip-address: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
    candlestickListener:
      possible_gap_in_updates_ms: 60_000
      check_time_period_multiplier: 10
    grpc:
      client:
        plaintext: true
        discovery:
          enabled: true
      server:
        port: 50052
        keep-alive-time: 3h
        max-inbound-message-size: 1024

    robot:
      usdCoin: USDT
      interval: TWELVE_HOURLY
      stopLoss: 0.01
      takeProfit: 3
      coinsCount: 1
      initialBalance: 30

    endpoints:
      health:
        enabled: true
        sensitive: false
