micronaut:
  application:
    name: database-persist
  server:
    port: 8081
datasources:
  default:
    url: jdbc:h2:file:./db/tradesDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: uaua
    password: ''
    schema-generate: CREATE
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
grpc:
  server:
    port: 50055
    keep-alive-time: 3h
    max-inbound-message-size: 1024
  client:
    plaintext: true
    discovery:
      enabled: true
consul:
  client:
    registration:
      enabled: true
      check.enabled: false
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
endpoints:
  health:
    enabled: true
    sensitive: false
