micronaut:
  application:
    name: backtest
datasources:
  default:
    url: jdbc:h2:file:./db/backtestDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: uaua
    password: ''
    schema-generate: CREATE
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
