micronaut:
  application:
    name: event-hub
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
grpc:
  server:
    port: 50051
    keep-alive-time: 3h
    max-inbound-message-size: 1024
  client:
    discovery:
      enabled: true